---
version: "2"
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/aurelia/tools/master/.eslintrc.json
    path: node_modules/aurelia-tools/.eslintrc.json
checks:
  method-lines:
    config:
      threshold: 30
  method-complexity:
    config:
      threshold: 7
engines:
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: true
  eslint:
    enabled: true
  stylelint:
    enabled: false
  htmlhint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- static/includes.html
- node_modules/
- coverage/
- dist/
- bower_components/
- webpack.config.js
