---
version: "2"
checks:
  method-lines:
    config:
      threshold: 32
  method-complexity:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 100
engines:
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40
  eslint:
    enabled: true
  stylelint:
    enabled: false
  htmlhint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- test/
- node_modules/
- coverage/
- dist/
