version: 2
jobs:
  build:
    working_directory: ~/frontend
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:8.7.0
    # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
      #- image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g yarn@latest && sudo yarn global add npm@latest && sudo yard global add codeclimate-test-reporter && sudo curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8.7.0
      #- image: mongo:3.4.4
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info'
      #- store_artifacts:
      #    path: test-results.xml
      #    prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/node:8.7.0
#      dependencies:
#        pre:
#          - curl -s https://raw.githubusercontent.com/chronogolf/circleci-google-chrome/master/use_chrome_stable_version.sh | bash
#          - npm install -g yarn codeclimate-test-reporter
#        override:
#          - yarn install

#general:
#  artifacts:
#    - ./coverage
#test:
#  post:
#    - codeclimate-test-reporter < coverage/lcov.info
